using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using OpenAI.Chat;
using UnityEngine;
using UnityEngine.AI;
using User_Emergency_Exit;

public class GeneratePath : MonoBehaviour {
    // Navmesh agent
    public NavMeshAgent agent;
    public Transform[] Exists;
    
    // Path Generation
    public GameObject waypoint, connector;
    private GameObject _container;
    private readonly List<GameObject> waypoints = new(), connectors = new();
    private readonly List<LineRenderer> connectorLines = new();
    
    // File Reader
    private static readonly string filepath = "/Users/tower/Documents/API Keys/OpenAI_ChatGPT_Key.txt";
    private readonly StreamReader reader = new (filepath);
    
    // Open AI
    private string apiKey;
    private ChatClient client;
    
    void Start() {
        // Set up GPT client
        apiKey = reader.ReadLine();
        client = new ChatClient("gpt-4o-mini", apiKey);
    }

    // ReSharper disable Unity.PerformanceAnalysis
    public void UpdatePath(Transform fire) {
        List<NavMeshPath> paths = new List<NavMeshPath>();
        
        // Get all the paths
        foreach (var exit in Exists) {
            NavMeshPath path = new NavMeshPath();
            bool  hasPath =  NavMesh.CalculatePath(transform.position, exit.position,
                NavMesh.AllAreas, path);
            if (hasPath) { paths.Add(path); }
        }
        
        // Get the total distance of each path and the distance of each
        // waypoint in that path to the fire.
        Debug.Log("Working");
        PathInformation[] pathInfo = new PathInformation[paths.Count];
        GetPathDistances(paths, pathInfo, fire); 
        
        // Convert paths to JSON.
        string jsonPaths = JsonConvert.SerializeObject(pathInfo);

        // Feed Data to ChatGPT
        // GetBestPath(paths, jsonPaths);
    }

    /// <summary>
    ///  Calculates the distance of each path generated by Unity's AI Navigation pathfinding algorithm.
    /// </summary>
    /// <param name="paths">Paths generated by Unity's AI Navigation pathfinding algorithm</param>
    /// <param name="pathInfo">Information regarding the path</param>
    private void GetPathDistances(List<NavMeshPath> paths, PathInformation[] pathInfo, Transform fire) {
        // Calculate distances for each path
        for (int i = 0; i < paths.Count; i++) {
            NavMeshPath path = paths[i];
            float d = 0;
            // Last point can be ignored due to being very close to the location of exit. 
            float[] d2 = new float[path.corners.Length - 1]; 
            
            for (int j = 0; j < path.corners.Length - 1; j++) {
                var point = path.corners[j];
                d += Vector3.Distance(point, path.corners[j+1]);
                d2[j] = Vector3.Distance(point, fire.position);
            }
            pathInfo[i] = new PathInformation(i, d, d2);
        }
    }
    

    
    
    /// <summary>
    /// Create and Updates the position of the emergency exit path
    /// based on what is the new shortest path. 
    /// </summary>
    /// <param name="path">Path to visualize</param>
    private void VisualizePath(NavMeshPath path) {
        Vector3[] corners = path.corners;
        
        // Create path components if they don't exist
        CreatePath(corners);
        // Update positions of path
        for (var i = 0; i < waypoints.Count; i++) {
            waypoints[i].transform.position = corners[i];
        }
        
        // Update the endpoints of connecting lines
        for (var i = 0; i < connectors.Count; i++) {
            connectorLines[i].SetPosition(0, corners[i]);
            connectorLines[i].SetPosition(1, corners[i+1]);
        }
    }
    
    /// <summary>
    /// Creates the components for displaying the emergency exit path.
    /// It stores this components (i.e. GameObjects) if a pool for later use.
    /// </summary>
    /// <param name="path"></param>
    private void CreatePath(Vector3[] path) {
        // Create a container if it doesn't exist
        if (_container == null) {
            _container = new GameObject("Exit Path");
        }
        
        // Create or activate waypoints objects
        // Creates extra waypoints if needed.
        var count = path.Length;
        for (int i = 0; i < count; i++) {
            if (i >= waypoints.Count) {
                GameObject wp = Instantiate(waypoint, Vector3.zero, Quaternion.identity, _container.transform);
                wp.name = "Waypoint_" + i;
                waypoints.Add(wp);
            }
            waypoints[i].SetActive(true); // Activate for usage
        }
        // Hide extra waypoint objects
        for (int i = count; i < waypoints.Count; i++) waypoints[i].SetActive(false);
        
        // Instantiate or activate trajectory connectors (i.e. LineRenders)
        for (int i = 0; i < count - 1; i++) {
            if (i >= connectors.Count) {
                // Instantiate new connectors for pooling
                GameObject conn = Instantiate(connector, Vector3.zero, Quaternion.identity, _container.transform);
                conn.name = "Connector_" + i;
                connectors.Add(conn);

                LineRenderer trajLine = conn.GetComponent<LineRenderer>();
                connectorLines.Add(trajLine);
            }
            // Activate for usage if, if not already;
            connectors[i].SetActive(true); 
        }
        // Hide extra connectors
        for (int i = count - 1; i < connectors.Count; i++) connectors[i].SetActive(false);
    }
}
